name: Java CI with Maven

on:
  push:
    branches: [ "main", "TicTacToe-Final" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code von GitHub auschecken
        uses: actions/checkout@v4

      - name: Java 17 einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Tests mit Maven ausführen
        run: mvn -B test